name: corremundos
description: Corremundos - Trip planner
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  auth_repository:
    path: packages/auth_repository
  bloc: ^8.0.1
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.5
  equatable: ^2.0.3
  flow_builder: ^0.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.0
  google_fonts: ^2.2.0
  intl: ^0.17.0
  uni_links: ^0.5.1
  utils:
    path: packages/utils

dev_dependencies:
  bloc_test: ^9.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
