name: corremundos
description: Corremundos - Trip planner
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  auth_repository:
    path: packages/auth_repository
  auto_size_text: ^3.0.0-nullsafety.0
  bloc: ^8.0.1
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^1.0.5 # TODO: there is a 3.x.x version
  dotted_border: ^2.0.0+2
  equatable: ^2.0.3
  file_picker: ^4.3.0
  flow_builder: ^0.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_cache_manager: ^3.3.0
  flutter_datetime_picker: ^1.5.1
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^9.2.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^1.3.2
  font_awesome_flutter: ^9.2.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.0
  google_fonts: ^2.2.0
  google_sign_in: ^5.2.3
  in_app_purchase: ^2.0.1
  intl: ^0.17.0
  loading_indicator: ^3.0.2
  pdf_render: ^1.0.18
  profile_repository:
    path: packages/profile_repository
  timeline_tile: ^2.0.0
  top_snackbar_flutter: ^1.0.2
  transparent_image: ^2.0.0
  trips_repository:
    path: packages/trips_repository
  unsplash_client: ^2.1.0+1
  url_launcher: ^6.0.18
  utils:
    path: packages/utils

dev_dependencies:
  bloc_test: ^9.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/corremundos_logo.png"

flutter_native_splash:
  color: "#5A17EE"
  image: assets/corremundos_logo.png
