name: form_inputs
description: Forms input validation
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  formz: ^0.4.0

dev_dependencies:
  test: ^1.16.4
  very_good_analysis: ^2.0.0